fixed issue#62
CodeFlow201/forestTreesTagging pull request #64
Opened 2021-04-07 05:31 UTC by anotherwebguy

# Description:

i have fixed issue #62 renderflex issue in signup screen

Fixes #62 

## Type of change:

- [x] Bug fix (non-breaking change which fixes an issue)

 
# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.

# Screenshots / Video:
![image](https://user-images.githubusercontent.com/66346161/113815311-92dd6600-9790-11eb-8332-23b6789742b7.png)

2021-04-07 05:55 UTC, anotherwebguy commented
> # Description:
> i have fixed issue #62 renderflex issue in signup screen
> 
> Fixes #62
> 
> ## Type of change:
> * [x]  Bug fix (non-breaking change which fixes an issue)
> 
> # Checklist:
> * [x]  My code follows the style guidelines of this project.
> * [x]  I have performed a self-review of my own code.
> * [x]  My changes generate no new warnings.
> 
> # Screenshots / Video:
> ![image](https://user-images.githubusercontent.com/66346161/113815311-92dd6600-9790-11eb-8332-23b6789742b7.png)

plz review @ghackg11

2021-04-08 03:00 UTC, anotherwebguy commented
Hey mentors and admin plz review my pr and add a label

2021-04-08 03:02 UTC, vaibhavarora102 commented
@anotherwebguy  we are looking into this, thanks for your patience

2021-04-08 04:26 UTC, Sameerkash requested changes
Please take a look, it'd be best if this is made optimal like I've mentioned.

2021-04-08 04:26 UTC, Sameerkash commented on lib/components/signUp.dart
> +                  height: MediaQuery.of(context).size.height * 0.01,
It'd be great if you created a helper class for MediaQuery instead of calling `MediaQuery.of(context)` every time. This makes the code too redundant.

2021-04-08 04:26 UTC, Sameerkash commented on lib/components/signUp.dart
> +                  height:  MediaQuery.of(context).size.height * 0.0005,
Just using MediaQuery's height wouldn't work in a wider aspect ration phone, we'd have to use breakpoints to assign heights, checkout [DevicePreivew](https://pub.dev/packages/device_preview) to test your code with different screen sized.

2021-04-08 07:07 UTC, anotherwebguy commented
Made changes

2021-04-08 07:23 UTC, Sameerkash approved these changes
Looks okay for now, would require a utility helper to for long term

2021-04-08 12:33 UTC, merged